---
dependency:
  name: galaxy

driver:
  name: podman

provisioner:
  name: ansible
  # log: true

verifier:
  name: ansible

scenario:
  name: ubuntu-22.04

platforms:
  - name: ubuntu-22.04
    image: ubuntu:22.04
