---
- name: Converge
  hosts: all

  tasks:
    - name: "Include christiangda.epel_repo"
      include_role:
        name: christiangda.epel_repo

    - name: "Include christiangda.awscli_configure"
      include_role:
        name: christiangda.awscli_configure

  roles:
    - role: christiangda.epel_repo
      when: >
        ansible_os_family == 'RedHat' and (
          ansible_distribution == 'CentOS' or
          ansible_distribution == 'RedHat' or
          ansible_distribution == 'Amazon'
        )
    - role: christiangda.awscli_configure
      vars:
        awscliconf_path: "/root"
        awscliconf_files:
          credentials:
            - AmazonCloudWatchAgent:
                aws_access_key_id: "AKIAIOSFODNN7EXAMPLE"
                aws_secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
          config:
            - profile AmazonCloudWatchAgent:
                region: eu-west-1
    - role: christiangda.amazon_cloudwatch_agent
      vars:
        cwa_agent_mode: "onPremise"
        cwa_profile: "AmazonCloudWatchAgent"
        cwa_aws_region: "eu-west-1"
